// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectDawnApi;

#nullable disable

namespace ProjectDawnApi.Migrations
{
    [DbContext(typeof(ProjectDawnDbContext))]
    [Migration("20251231063650_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ProjectDawnApi.FarmDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("ProjectDawnApi.FarmVisitorDM", b =>
                {
                    b.Property<int>("FarmId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("FarmId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("FarmVisitors");
                });

            modelBuilder.Entity("ProjectDawnApi.InventoryDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("ProjectDawnApi.InventoryItemDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("ProjectDawnApi.PlacedObjectDM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("FarmId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("PlacedObjects");
                });

            modelBuilder.Entity("ProjectDawnApi.PlayerDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ProjectDawnApi.RefreshTokenDM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProjectDawnApi.FarmDM", b =>
                {
                    b.HasOne("ProjectDawnApi.PlayerDM", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProjectDawnApi.FarmVisitorDM", b =>
                {
                    b.HasOne("ProjectDawnApi.FarmDM", "Farm")
                        .WithMany("Visitors")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectDawnApi.PlayerDM", "PlayerDataModel")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ProjectDawnApi.TransformationDM", "Transformation", b1 =>
                        {
                            b1.Property<int>("FarmVisitorDMFarmId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FarmVisitorDMPlayerId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("positionX")
                                .HasColumnType("REAL");

                            b1.Property<float>("positionY")
                                .HasColumnType("REAL");

                            b1.Property<float>("positionZ")
                                .HasColumnType("REAL");

                            b1.Property<float>("rotationX")
                                .HasColumnType("REAL");

                            b1.Property<float>("rotationY")
                                .HasColumnType("REAL");

                            b1.Property<float>("rotationZ")
                                .HasColumnType("REAL");

                            b1.HasKey("FarmVisitorDMFarmId", "FarmVisitorDMPlayerId");

                            b1.ToTable("FarmVisitors");

                            b1.WithOwner()
                                .HasForeignKey("FarmVisitorDMFarmId", "FarmVisitorDMPlayerId");
                        });

                    b.Navigation("Farm");

                    b.Navigation("PlayerDataModel");

                    b.Navigation("Transformation")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectDawnApi.InventoryDM", b =>
                {
                    b.HasOne("ProjectDawnApi.PlayerDM", "Player")
                        .WithOne("Inventory")
                        .HasForeignKey("ProjectDawnApi.InventoryDM", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProjectDawnApi.InventoryItemDM", b =>
                {
                    b.HasOne("ProjectDawnApi.InventoryDM", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ProjectDawnApi.PlacedObjectDM", b =>
                {
                    b.HasOne("ProjectDawnApi.FarmDM", null)
                        .WithMany("PlacedObjects")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ProjectDawnApi.TransformationDM", "Transformation", b1 =>
                        {
                            b1.Property<Guid>("PlacedObjectDMId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("positionX")
                                .HasColumnType("REAL");

                            b1.Property<float>("positionY")
                                .HasColumnType("REAL");

                            b1.Property<float>("positionZ")
                                .HasColumnType("REAL");

                            b1.Property<float>("rotationX")
                                .HasColumnType("REAL");

                            b1.Property<float>("rotationY")
                                .HasColumnType("REAL");

                            b1.Property<float>("rotationZ")
                                .HasColumnType("REAL");

                            b1.HasKey("PlacedObjectDMId");

                            b1.ToTable("PlacedObjects");

                            b1.WithOwner()
                                .HasForeignKey("PlacedObjectDMId");
                        });

                    b.Navigation("Transformation")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectDawnApi.RefreshTokenDM", b =>
                {
                    b.HasOne("ProjectDawnApi.PlayerDM", "Player")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProjectDawnApi.FarmDM", b =>
                {
                    b.Navigation("PlacedObjects");

                    b.Navigation("Visitors");
                });

            modelBuilder.Entity("ProjectDawnApi.InventoryDM", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProjectDawnApi.PlayerDM", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
